name: Build Kernel (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc libncurses5-dev bison flex libssl-dev

      - name: Run build script
        run: |
          chmod +x build-droidian.sh
          ./build-droidian.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-output
          path: |
            build/out/*
            *.img
            *.bin
            *.tar.gz
            *kernel
            *Image
